# Generated by Django 5.2 on 2025-04-06 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_barcode_alter_product_sku'),
        ('transaction', '0003_remove_transaction_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.product'),
        ),
    ]
